1. popularity base
2. content base item similarity
3. collaborative user similarity
4. hybrid (2+3)
5. classification base binary
6. object detection


In [ ]:
# https://www.youtube.com/watch?v=shtPVU5zXkM
# https://github.com/Dhruv-saxena-25/flipkart
# https://github.com/campusx-official/fashion-recommender-system

In [1]:
import tensorflow
from tensorflow.keras.preprocessing import image
from tensorflow.keras.layers import GlobalMaxPooling2D
from tensorflow.keras.applications.resnet50 import ResNet50,preprocess_input
import numpy as np
from numpy.linalg import norm
import os
from tqdm import tqdm
import pickle

In [2]:
model = ResNet50(weights='imagenet',include_top=False,input_shape=(224,224,3))
model.trainable = False


In [3]:
model = tensorflow.keras.Sequential([
    model,
    GlobalMaxPooling2D()
])

In [4]:
print(model.summary())


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ resnet50 (Functional)           │ (None, 7, 7, 2048)     │    23,587,712 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_max_pooling2d            │ (None, 2048)           │             0 │
│ (GlobalMaxPooling2D)            │                        │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 23,587,712 (89.98 MB)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 23,587,712 (89.98 MB)

None


In [5]:
def extract_features(img_path,model):
    img = image.load_img(img_path,target_size=(224,224))
    img_array = image.img_to_array(img)
    expanded_img_array = np.expand_dims(img_array, axis=0)
    preprocessed_img = preprocess_input(expanded_img_array)
    result = model.predict(preprocessed_img).flatten()
    normalized_result = result / norm(result)

    return normalized_result

In [6]:
os.listdir

<function nt.listdir(path=None)>

In [9]:
filenames = []

for file in os.listdir('../artifacts/images'):
    filenames.append(os.path.join('artifacts','images',file))

In [10]:
filenames

['artifacts\\images\\pant1.jpg',
 'artifacts\\images\\pant2.jpg',
 'artifacts\\images\\pant3.jpg',
 'artifacts\\images\\pant4.jpg',
 'artifacts\\images\\pant5.jpg',
 'artifacts\\images\\shirt1.jpg',
 'artifacts\\images\\shirt2.jpg',
 'artifacts\\images\\shirt3.jpg',
 'artifacts\\images\\shirt4.jpg',
 'artifacts\\images\\shirt5.jpg',
 'artifacts\\images\\tshirt1.jpg']

In [15]:
filenames2 = []

for file in os.listdir('images'):
    filenames2.append(os.path.join('images',file))

In [16]:
feature_list = []


for file in tqdm(filenames2):
    feature_list.append(extract_features(file,model))

  0%|          | 0/11 [00:00<?, ?it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step


  9%|▉         | 1/11 [00:02<00:27,  2.70s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step


 18%|█▊        | 2/11 [00:02<00:11,  1.25s/it]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step


 27%|██▋       | 3/11 [00:03<00:06,  1.30it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step


 36%|███▋      | 4/11 [00:03<00:03,  1.80it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step


 45%|████▌     | 5/11 [00:03<00:02,  2.24it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step


 55%|█████▍    | 6/11 [00:03<00:01,  2.69it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step


 64%|██████▎   | 7/11 [00:04<00:01,  3.12it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step


 73%|███████▎  | 8/11 [00:04<00:00,  3.58it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step


 82%|████████▏ | 9/11 [00:04<00:00,  3.94it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 255ms/step


 91%|█████████ | 10/11 [00:04<00:00,  3.56it/s]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step


100%|██████████| 11/11 [00:05<00:00,  2.20it/s]


In [17]:
feature_list

[array([0.01781286, 0.03276036, 0.00301866, ..., 0.        , 0.00275664,
        0.04756737], dtype=float32),
 array([0.02117556, 0.01312066, 0.00316607, ..., 0.0235543 , 0.00585177,
        0.06458791], dtype=float32),
 array([0.02799237, 0.00744709, 0.        , ..., 0.01733447, 0.01864951,
        0.0419126 ], dtype=float32),
 array([0.00627032, 0.02679138, 0.        , ..., 0.02175038, 0.00025124,
        0.01328407], dtype=float32),
 array([0.01427418, 0.00942373, 0.        , ..., 0.02103913, 0.00069038,
        0.03834948], dtype=float32),
 array([0.00093782, 0.00431563, 0.0010758 , ..., 0.01106163, 0.01293024,
        0.05574945], dtype=float32),
 array([0.01526882, 0.00823358, 0.00801689, ..., 0.01673536, 0.01527698,
        0.00805513], dtype=float32),
 array([0.00863065, 0.02698559, 0.        , ..., 0.01257337, 0.        ,
        0.01593616], dtype=float32),
 array([0.01547045, 0.03741662, 0.        , ..., 0.0145354 , 0.00757444,
        0.01175345], dtype=float32),
 array([0.

In [18]:
pickle.dump(feature_list,open('../artifacts/embeddings.pkl','wb'))
pickle.dump(filenames,open('../artifacts/filenames.pkl','wb'))

In [16]:
import pickle
import tensorflow
import numpy as np
from numpy.linalg import norm
from tensorflow.keras.preprocessing import image
from tensorflow.keras.layers import GlobalMaxPooling2D
from tensorflow.keras.applications.resnet50 import ResNet50,preprocess_input
from sklearn.neighbors import NearestNeighbors
import cv2

In [29]:
feature_list = np.array(pickle.load(open('embeddings.pkl','rb')))
filenames = pickle.load(open('filenames.pkl','rb'))

In [30]:
feature_list

array([[0.01781286, 0.03276036, 0.00301866, ..., 0.        , 0.00275664,
        0.04756737],
       [0.02117556, 0.01312066, 0.00316607, ..., 0.0235543 , 0.00585177,
        0.06458791],
       [0.02799237, 0.00744709, 0.        , ..., 0.01733447, 0.01864951,
        0.0419126 ],
       ...,
       [0.01547045, 0.03741662, 0.        , ..., 0.0145354 , 0.00757444,
        0.01175345],
       [0.00628402, 0.02655974, 0.00218449, ..., 0.02051407, 0.00542202,
        0.00389995],
       [0.01116261, 0.05799199, 0.0040314 , ..., 0.02293215, 0.00380538,
        0.0385583 ]], dtype=float32)

In [19]:
filenames

['artifacts\\images\\pant1.jpg',
 'artifacts\\images\\pant2.jpg',
 'artifacts\\images\\pant3.jpg',
 'artifacts\\images\\pant4.jpg',
 'artifacts\\images\\pant5.jpg',
 'artifacts\\images\\shirt1.jpg',
 'artifacts\\images\\shirt2.jpg',
 'artifacts\\images\\shirt3.jpg',
 'artifacts\\images\\shirt4.jpg',
 'artifacts\\images\\shirt5.jpg',
 'artifacts\\images\\tshirt1.jpg']

In [32]:
img = image.load_img('sample/shirt.jpg',target_size=(224,224))
img_array = image.img_to_array(img)
expanded_img_array = np.expand_dims(img_array, axis=0)
preprocessed_img = preprocess_input(expanded_img_array)
result = model.predict(preprocessed_img).flatten()
normalized_result = result / norm(result)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step


In [33]:
result

array([ 1.4817466, 13.5114   ,  2.172598 , ...,  3.9420702,  2.655559 ,
        2.3561504], dtype=float32)

In [34]:
norm(result)

np.float32(267.3002)

In [35]:
normalized_result

array([0.00554338, 0.05054766, 0.00812793, ..., 0.01474773, 0.00993474,
       0.00881462], dtype=float32)

In [40]:
neighbors = NearestNeighbors(n_neighbors=3,algorithm='brute',metric='euclidean')
neighbors.fit(feature_list)


NearestNeighbors(algorithm='brute', metric='euclidean', n_neighbors=3)

In [41]:
distances,indices = neighbors.kneighbors([normalized_result])

In [42]:
distances

array([[0.64169753, 0.77293825, 0.77745986]])

In [43]:
indices

array([[9, 6, 7]])

In [44]:
indices[0]

array([9, 6, 7])

In [45]:
indices[0][1:3]

array([6, 7])

In [ ]:
for file in indices[0][0:3]:
    temp_img = cv2.imread(filenames[file])
    cv2.imshow('output',cv2.resize(temp_img,(512,512)))
    cv2.waitKey(0)